language: objective-c
before_install:
  - gem install xcpretty
#  - brew update
#  - brew uninstall xctool
#  - brew install -v --HEAD xctool
  - cd Example && pod install && cd -
script:
  - chmod +x ./script/run_pretty_tests.sh
  - ./script/run_pretty_tests.sh
